windows: Build with OpenSSL 3.0.
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>

diff --git a/utilities/ovs-pki.in b/utilities/ovs-pki.in
--- a/utilities/ovs-pki.in
+++ b/utilities/ovs-pki.in
@@ -57,6 +57,69 @@ FreeBSD|NetBSD|Darwin)
     ;;
 esac
 
+case $(uname -s) in
+MINGW*|MSYS*)
+    chmod()
+    {
+        PERM=$1
+        FILE=$2
+
+        case "${PERM}" in
+        *700)
+            # Reset all inherited permissions and grant full access to
+            # the "Creator Owner".
+            icacls "${FILE}" /inheritance:r /grant:r '*S-1-3-0:(OI)(CI)F'
+            ;;
+        *750)
+            # Reset all inherited permissions, grant full access to the
+            # "Creator Owner" and a read+execute access to the "Creator Group".
+            icacls "${FILE}" /inheritance:r /grant:r \
+                '*S-1-3-0:(OI)(CI)F' '*S-1-3-1:(OI)(CI)RX'
+            ;;
+        *)
+            echo >&2 "Unable to set ${PERM} mode for ${FILE}."
+            exit 1
+            ;;
+        esac
+    }
+
+    mkdir()
+    {
+        ARG_P=
+        PERM=
+        for arg; do
+            shift
+            case ${arg} in
+            -m?*)
+                PERM=${arg#??}
+                continue
+                ;;
+            -m)
+                PERM=$1
+                shift
+                continue
+                ;;
+            -p)
+                ARG_P=-p
+                continue
+                ;;
+            *)
+                set -- "$@" "${arg}"
+                ;;
+            esac
+        done
+
+        command mkdir ${ARG_P} $@
+        if [ ${PERM} ]; then
+            for dir; do
+                shift
+                chmod ${PERM} ${dir}
+            done
+        fi
+    }
+    ;;
+esac
+
 for option; do
     # This option-parsing mechanism borrowed from a Autoconf-generated
     # configure script under the following license:
